# Generated by Django 3.1.3 on 2020-11-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='image',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
