# Generated by Django 3.1.3 on 2020-11-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stv', '0002_cliente_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(default='null', upload_to='')),
                ('web', models.CharField(max_length=100)),
            ],
        ),
    ]
